# Generated by Django 3.2.19 on 2023-09-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0083_alter_salescreditnote_customer'),
    ]

    operations = [
        
    ]
