# Generated by Django 3.2.19 on 2023-09-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0084_rename_customer_salescreditnote_customr'),
    ]

    operations = [
       
    ]
