# Generated by Django 3.2.19 on 2023-09-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0087_alter_salescreditnote_customer'),
    ]

    operations = [
        
    ]
