# Generated by Django 3.2.19 on 2023-09-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0088_alter_salescreditnote_customer'),
    ]

    operations = [
        
    ]
