# Generated by Django 3.2.19 on 2023-09-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0089_alter_salescreditnote_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescreditnote1',
            name='scredit',
        ),
        migrations.DeleteModel(
            name='salescreditnote',
        ),
        migrations.DeleteModel(
            name='salescreditnote1',
        ),
    ]
