# Generated by Django 3.2.19 on 2023-09-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0091_salescreditnote_salescreditnote1'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditnote',
            name='customr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
