# Generated by Django 3.2.19 on 2023-09-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0092_salescreditnote_customr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescreditnote',
            name='custom',
        ),
    ]
