# Generated by Django 3.2.19 on 2023-09-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0093_remove_salescreditnote_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salescreditnote',
            old_name='customr',
            new_name='customer',
        ),
    ]
