# Generated by Django 3.2.19 on 2023-09-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0095_salescreditnote_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gstin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
