# Generated by Django 3.2.19 on 2023-09-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230907_0935'),
        ('app1', '0097_auto_20230908_1055'),
    ]

    operations = [
    ]
